variable "aws_region" { default = "us-east-1" }
variable "project" { default = "cloudcart" }
variable "vpc_cidr" { default = "10.0.0.0/16" }
variable "public_subnets" { default = ["10.0.1.0/24", "10.0.2.0/24"] }
variable "private_subnets" { default = ["10.0.10.0/24", "10.0.11.0/24"] }
variable "instance_type" { default = "t3.micro" }
variable "desired_capacity" { default = 2 }
variable "dockerhub_username" { default = "augustthelabel" } # replace
variable "docker_image" { default = "cloudcart-sample" }
variable "docker_image_tag" { default = "latest" }
variable "db_username" { default = "cloudcart" }
variable "db_allocated_storage" { default = 20 }
